
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 18 22:27:19 CST 2013
//----------------------------------------------------

package syntactic;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int DIGIT_OR = 11;
  public static final int SHR_ASSIGN = 22;
  public static final int SHR = 14;
  public static final int DIVIDE = 5;
  public static final int XOR_ASSIGN = 24;
  public static final int LBRACKET = 39;
  public static final int CHAR = 48;
  public static final int SHL = 13;
  public static final int GE = 31;
  public static final int XOR = 12;
  public static final int CONTINUE = 56;
  public static final int LPAREN = 35;
  public static final int INT = 49;
  public static final int FOR = 55;
  public static final int MINUS = 3;
  public static final int RPAREN = 36;
  public static final int SIZEOF = 59;
  public static final int SEMICOLON = 41;
  public static final int SUB_ASSIGN = 20;
  public static final int NOT = 34;
  public static final int AND = 33;
  public static final int LT = 28;
  public static final int OR = 32;
  public static final int ELLIPSIS = 43;
  public static final int COMMA = 42;
  public static final int INC = 7;
  public static final int TYPEDEF = 46;
  public static final int PLUS = 2;
  public static final int IF = 52;
  public static final int ASSIGN = 15;
  public static final int ID = 60;
  public static final int PTR = 45;
  public static final int LE = 30;
  public static final int ADD_ASSIGN = 19;
  public static final int EOF = 0;
  public static final int RETURN = 58;
  public static final int RBRACKET = 40;
  public static final int STRINGCONSTANT = 63;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 21;
  public static final int CHARCONSTANT = 64;
  public static final int NUMBER = 61;
  public static final int MOD = 6;
  public static final int BREAK = 57;
  public static final int VOID = 47;
  public static final int EQ = 26;
  public static final int DIV_ASSIGN = 17;
  public static final int MOD_ASSIGN = 18;
  public static final int TIMES = 4;
  public static final int UNION = 51;
  public static final int ELSE = 53;
  public static final int LBRACE = 37;
  public static final int AND_ASSIGN = 23;
  public static final int POINT = 44;
  public static final int WHILE = 54;
  public static final int OR_ASSIGN = 25;
  public static final int RBRACE = 38;
  public static final int NE = 27;
  public static final int MUL_ASSIGN = 16;
  public static final int DIGIT_NOT = 9;
  public static final int DIGIT_AND = 10;
  public static final int DEC = 8;
  public static final int TYPEDEFNAME = 62;
  public static final int STRUCT = 50;
  public static final int GT = 29;
}

